version: '3.9'
services:
  database:
    container_name: matcha_database
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DB_PASS}
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: matcha_backend
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    container_name: matcha_frontend
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
